config/routes.rb
Rails.application.routes.draw do
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  belongs_to :ingredient
  belongs_to :cocktail
  validates_uniqueness_of :cocktail_id, scope: :ingredient_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find params[:id]
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
  @cocktail = Cocktail.new(cocktail_params)
      if @cocktail.save
        redirect_to cocktail_path(@cocktail)
      else
        render :new
      end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find params[:cocktail_id]
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.ingredient_id = params["dose"]["ingredient_id"].to_i
    @dose.cocktail = Cocktail.find params[:cocktail_id]
      if @dose.save
        redirect_to cocktail_path(@dose.cocktail)
      else
        render :new
      end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail_id)
  end

private
  def dose_params
    params.require(:dose).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="navbar-lewagon"></div>

<div class="banner">
  <div class="titlez">
    <h1>Lorem<br>Ipsum<br></h1>
  </div>
  <div class="new-cocktail">
    <div> <%= link_to 'Create your cocktail!', new_cocktail_path %> </div>
  </div>
</div>

<div class="space">
  <h5><i>"Work is the curse of the drinking classes."</i> ~ Oscar Wilde</h5>
</div>

<div class="cards">
<% @cocktails.each do |cocktail|%>
  <div>
    <div class="card">
      <h3 id="names"><%=link_to cocktail.name.capitalize, cocktail_path(cocktail)%></h3>
      <%= cl_image_tag cocktail.photo, height: 300, width: 400, crop: :fill %>
    </div>
  </div>
<% end %>
</div>

app/views/cocktails/new.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.submit "add a new cocktail", class: "btn btn-primary" %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
<% end %>

app/views/cocktails/show.html.erb
<h1><%=@cocktail.name%></h1>

<div class="">
<% @cocktail.doses.each do |dose| %>
<p><%= dose.ingredient.name %></p>
<p><%= dose.description %></p>
<div> <%= link_to 'Delete ingredient!', dose_path(dose),
      method: :delete,
      data: { confirm: "Are you sure?" } %></div>
</div>
<% end  %>
</div>cards
<div class="new-ingredient">
  <div> <%= link_to 'Add an ingredient!', new_cocktail_dose_path(@cocktail) %> </div>
  <div> <%= link_to 'Go back', cocktails_path %> </div>
</div>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose],:url =>  cocktail_doses_path, :method => :post do |f| %>
<% if @dose.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @dose.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.button :submit %>
<% end %>

  <div> <%= link_to 'Go back to the cocktail!', cocktail_path(@cocktail) %> </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>